### ISSUE TITLE
dropdown not loading with images and phonenumbers

### ISSUE THREAD

**Issue by Karthickgreets99** [hodgepodgers/ng-intl-tel-input#47]
i am trying to implement ng-intl-tel-input  plugin but dropdown not loading with images and phonenumbers, no erros are showing.. please help

**Comment by bighappyface** [comment]
Pay close attention to the example implementation demonstrated in index.html:

https://github.com/hodgepodgers/ng-intl-tel-input/blob/master/index.html

The various css and js files are key for full operation, however, you will only need to use our minified distribution file instead of the inidividual source files for this module.
